version: "3"
services:
  database:
    image: adrianat10/hw-db
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    volumes:
      - dbvolume:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - webnet
    #command: "mysql -u homework -phomework < /home/db_script"
  app:
    image: adrianat10/hw-app
    deploy:
      replicas: 6
    ports:
      - "3000:3000"
    networks:
      - webnet
    command: "node app/server.js database --server.urls http://*:3000"
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
networks:
  webnet:
volumes:
  dbvolume:
